import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// Renders an HTML string with the browser (full Bangla/৳ text shaping, which
// jsPDF's built-in fonts cannot do) and saves it as an A4 PDF image.
// IMPORTANT: the HTML must use only inline styles with hex/rgb colors —
// Tailwind 4 classes compile to oklch() which html2canvas cannot parse.
export async function downloadHtmlAsPdf(html, fileName) {
  const host = document.createElement('div');
  host.style.cssText =
    'position:fixed;left:-10000px;top:0;width:794px;background:#ffffff;color:#111827;' +
    "font-family:'Segoe UI','Nirmala UI','Noto Sans Bengali','Hind Siliguri',sans-serif;";
  host.innerHTML = html;
  document.body.appendChild(host);
  try {
    const canvas = await html2canvas(host, { scale: 2, backgroundColor: '#ffffff', logging: false });
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageW = pdf.internal.pageSize.getWidth();
    const pageH = pdf.internal.pageSize.getHeight();
    const imgH = (canvas.height * pageW) / canvas.width;
    let offset = 0;
    let page = 0;
    while (offset < imgH) {
      if (page > 0) pdf.addPage();
      pdf.addImage(canvas, 'PNG', 0, -offset, pageW, imgH);
      offset += pageH;
      page += 1;
    }
    pdf.save(fileName);
  } finally {
    if (window.__keepPdfHost) {
      // debug aid for UI audits: leave the rendered paper on screen
      host.style.cssText = 'position:fixed;left:0;top:0;width:794px;background:#fff;z-index:99999;' + host.style.fontFamily;
    } else {
      host.remove();
    }
  }
}

const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const tableHtml = (head, rows, boldRows = []) => {
  const th = head
    .map((h, i) =>
      `<th style="border:1px solid #94a3b8;background:#0e7490;color:#ffffff;padding:6px 10px;font-size:12.5px;text-align:${i === 0 ? 'left' : 'right'};">${esc(h)}</th>`)
    .join('');
  const body = rows
    .map((cells, ri) => {
      const bold = boldRows.includes(ri);
      const tds = cells
        .map((c, i) =>
          `<td style="border:1px solid #cbd5e1;padding:5px 10px;font-size:12px;color:#111827;text-align:${i === 0 ? 'left' : 'right'};${bold ? 'font-weight:700;background:#f1f5f9;' : ''}white-space:pre-wrap;">${esc(c)}</td>`)
        .join('');
      return `<tr>${tds}</tr>`;
    })
    .join('');
  return `<table style="width:100%;border-collapse:collapse;"><thead><tr>${th}</tr></thead><tbody>${body}</tbody></table>`;
};

// Multi-table statement paper: each section = { title, head, rows, boldRows }.
export function multiSectionHtml({ entityName, title, subtitle, sections }) {
  const parts = sections
    .map(s =>
      `<div style="margin-top:18px;">
        ${s.title ? `<div style="font-size:13px;font-weight:700;color:#0e7490;margin-bottom:6px;">${esc(s.title)}</div>` : ''}
        ${tableHtml(s.head, s.rows, s.boldRows || [])}
      </div>`)
    .join('');
  return `
    <div style="padding:36px 40px;">
      <div style="text-align:center;margin-bottom:6px;">
        <div style="font-size:20px;font-weight:700;color:#111827;">${esc(entityName || 'TakaKhata')}</div>
        <div style="font-size:16px;font-weight:600;color:#0e7490;margin-top:2px;">${esc(title)}</div>
        <div style="font-size:11.5px;color:#6b7280;margin-top:2px;">${esc(subtitle)}</div>
      </div>
      ${parts}
      <div style="font-size:10px;color:#9ca3af;margin-top:14px;text-align:right;">Generated by TakaKhata · ${new Date().toLocaleDateString('en-GB')}</div>
    </div>`;
}

// Builds a clean statement "paper": centered header + a bordered table.
// rows: array of string[] matching head's length; boldRows: row indexes to emphasize.
export function statementHtml({ entityName, title, subtitle, head, rows, boldRows = [] }) {
  const th = head
    .map((h, i) =>
      `<th style="border:1px solid #94a3b8;background:#0e7490;color:#ffffff;padding:6px 10px;font-size:13px;text-align:${i === 0 ? 'left' : 'right'};">${esc(h)}</th>`)
    .join('');
  const body = rows
    .map((cells, ri) => {
      const bold = boldRows.includes(ri);
      const tds = cells
        .map((c, i) =>
          // explicit color on every cell: the app's dark-theme CSS otherwise paints table text white
          `<td style="border:1px solid #cbd5e1;padding:5px 10px;font-size:12.5px;color:#111827;text-align:${i === 0 ? 'left' : 'right'};${bold ? 'font-weight:700;background:#f1f5f9;' : ''}white-space:pre-wrap;">${esc(c)}</td>`)
        .join('');
      return `<tr>${tds}</tr>`;
    })
    .join('');
  return `
    <div style="padding:36px 40px;">
      <div style="text-align:center;margin-bottom:18px;">
        <div style="font-size:20px;font-weight:700;color:#111827;">${esc(entityName || 'TakaKhata')}</div>
        <div style="font-size:16px;font-weight:600;color:#0e7490;margin-top:2px;">${esc(title)}</div>
        <div style="font-size:11.5px;color:#6b7280;margin-top:2px;">${esc(subtitle)}</div>
      </div>
      <table style="width:100%;border-collapse:collapse;">
        <thead><tr>${th}</tr></thead>
        <tbody>${body}</tbody>
      </table>
      <div style="font-size:10px;color:#9ca3af;margin-top:14px;text-align:right;">Generated by TakaKhata · ${new Date().toLocaleDateString('en-GB')}</div>
    </div>`;
}
