import { useState, useMemo } from 'react';
import { useEntityTable } from '../hooks/useEntityTable';
import { useAccounts } from '../context/AccountContext';
import { useCategories } from '../hooks/useCategories';
import { useAuth } from '../context/AuthContext';
import { useEntity } from '../context/EntityContext';
import { supabase } from '../lib/supabase';
import StatCard from '../components/StatCard';
import { downloadHtmlAsPdf, multiSectionHtml } from '../lib/htmlPdf';
import { amountInWords } from '../lib/amountInWords';
import {
  Home, Plus, Phone, Edit2, Trash2, Building2, Wallet,
  MessageCircle, FileText, Receipt, ChevronDown, ChevronUp, LogOut, Wrench
} from 'lucide-react';

const fmt = (n) => `৳${Math.round(Number(n || 0)).toLocaleString()}`;
const today = () => new Date().toISOString().split('T')[0];
const monthKey = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-01`;
const monthLabel = (k, opts = { month: 'short', year: '2-digit' }) => new Date(k).toLocaleDateString('en-US', opts);

// last 12 months, newest first
const last12Months = () => {
  const now = new Date();
  return Array.from({ length: 12 }, (_, i) => {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    return { key: monthKey(d), label: monthLabel(monthKey(d)) };
  });
};

const intlPhone = (phone) => {
  const digits = (phone || '').replace(/\D/g, '');
  if (digits.startsWith('880')) return digits;
  if (digits.startsWith('0')) return '88' + digits;
  return digits;
};

const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Standalone rent receipt paper (inline styles only — html2canvas can't parse oklch)
const receiptHtml = ({ entityName, unit, payment }) => {
  const rentPart = Number(payment.amount) - Number(payment.charge_amount || 0);
  const rows = [
    ['Rent — ' + monthLabel(payment.rent_month, { month: 'long', year: 'numeric' }), fmt(rentPart)],
    ...(Number(payment.charge_amount) > 0
      ? [[`Charges${payment.charge_note ? ` (${payment.charge_note})` : ''}`, fmt(payment.charge_amount)]]
      : [])
  ];
  const trs = rows.map(([l, v]) =>
    `<tr><td style="border:1px solid #cbd5e1;padding:7px 12px;font-size:13px;color:#111827;">${esc(l)}</td>
      <td style="border:1px solid #cbd5e1;padding:7px 12px;font-size:13px;color:#111827;text-align:right;">${esc(v)}</td></tr>`).join('');
  return `
    <div style="padding:36px 44px;">
      <div style="text-align:center;">
        <div style="font-size:20px;font-weight:700;color:#111827;">${esc(entityName || 'TakaKhata')}</div>
        <div style="font-size:15px;font-weight:600;color:#0f766e;margin-top:2px;">RENT RECEIPT</div>
        <div style="font-size:11px;color:#6b7280;margin-top:2px;">Receipt No: ${esc(payment.id.slice(0, 8).toUpperCase())} · Date: ${esc(new Date(payment.paid_date).toLocaleDateString('en-GB'))}</div>
      </div>
      <div style="margin-top:18px;font-size:13px;color:#111827;line-height:1.7;">
        Received with thanks from <strong>${esc(unit.tenant_name || '—')}</strong>,
        tenant of <strong>${esc(unit.name)}</strong>, the following payment:
      </div>
      <table style="width:100%;border-collapse:collapse;margin-top:12px;">
        <tbody>${trs}
          <tr><td style="border:1px solid #94a3b8;padding:7px 12px;font-size:13px;font-weight:700;background:#f1f5f9;color:#111827;">Total Received</td>
            <td style="border:1px solid #94a3b8;padding:7px 12px;font-size:13px;font-weight:700;background:#f1f5f9;color:#111827;text-align:right;">${esc(fmt(payment.amount))}</td></tr>
        </tbody>
      </table>
      <div style="margin-top:10px;font-size:12px;color:#374151;">In words: <em>${esc(amountInWords(Number(payment.amount)))}</em></div>
      <div style="display:flex;justify-content:space-between;margin-top:64px;">
        <div style="border-top:1px solid #9ca3af;padding-top:5px;font-size:11.5px;color:#374151;width:200px;text-align:center;">Tenant's Signature</div>
        <div style="border-top:1px solid #9ca3af;padding-top:5px;font-size:11.5px;color:#374151;width:200px;text-align:center;">Landlord's Signature</div>
      </div>
      <div style="font-size:10px;color:#9ca3af;margin-top:28px;text-align:right;">Generated by TakaKhata · ${new Date().toLocaleDateString('en-GB')}</div>
    </div>`;
};

export default function Rent() {
  const { user } = useAuth();
  const { currentEntity } = useEntity();
  const { rows: units, loading, addRow, updateRow, deleteRow } = useEntityTable('rental_units');
  const { rows: payments, addRow: addPayment, deleteRow: deletePayment, fetchRows: fetchPayments } = useEntityTable('rent_payments', { orderBy: 'rent_month' });
  const { rows: revisions, addRow: addRevision, updateRow: updateRevision } = useEntityTable('rent_revisions', { orderBy: 'effective_from' });
  const { rows: tenancies, addRow: addTenancy } = useEntityTable('unit_tenancies', { orderBy: 'end_date' });
  const { rows: unitExpenses, addRow: addUnitExpense, deleteRow: deleteUnitExpense } = useEntityTable('rent_unit_expenses', { orderBy: 'date' });
  const { accounts, fetchAccounts } = useAccounts();
  const { categories } = useCategories();
  const incomeCategories = categories?.filter(c => c.type === 'income') || [];
  const expenseCategories = categories?.filter(c => c.type === 'expense') || [];

  const [isAdding, setIsAdding] = useState(false);
  const [editing, setEditing] = useState(null);
  const [collecting, setCollecting] = useState(null); // { unit, month }
  const [monthView, setMonthView] = useState(null);   // { unit, month }
  const [settling, setSettling] = useState(null);     // unit
  const [expandedId, setExpandedId] = useState(null); // unit id with details open
  const [stmtOpen, setStmtOpen] = useState(false);
  const [stmtYear, setStmtYear] = useState(new Date().getFullYear());

  const initialForm = { name: '', tenant_name: '', tenant_phone: '', monthly_rent: '', advance_deposit: '', rent_start: '', notes: '', is_active: true, rent_effective: new Date().toISOString().slice(0, 7) };
  const [form, setForm] = useState(initialForm);
  const initialCollect = { amount: '', charge_amount: '', charge_note: '', account_id: '', category_id: '', date: today(), log_income: true };
  const [collectForm, setCollectForm] = useState(initialCollect);
  const initialSettle = { end_date: today(), dues: '', log_refund: true, account_id: '', category_id: '', log_dues_income: false, dues_category_id: '', notes: '' };
  const [settleForm, setSettleForm] = useState(initialSettle);
  const initialExpense = { date: today(), amount: '', description: '', pay_from_account: false, account_id: '', category_id: '' };
  const [expForm, setExpForm] = useState(initialExpense);

  const months = useMemo(() => last12Months(), []);
  const thisMonthKey = monthKey(new Date());

  // unitId|month → { paid, list } (several partial payments can share a month)
  const payAgg = useMemo(() => {
    const map = new Map();
    for (const p of payments) {
      const k = `${p.unit_id}|${p.rent_month}`;
      const e = map.get(k) || { paid: 0, list: [] };
      e.paid += Number(p.amount);
      e.list.push(p);
      map.set(k, e);
    }
    return map;
  }, [payments]);

  const revsByUnit = useMemo(() => {
    const map = new Map();
    for (const r of revisions) {
      if (!map.has(r.unit_id)) map.set(r.unit_id, []);
      map.get(r.unit_id).push(r);
    }
    for (const list of map.values()) list.sort((a, b) => b.effective_from.localeCompare(a.effective_from));
    return map;
  }, [revisions]);

  // Expected rent for a month = latest revision effective on/before it (fallback: base rent)
  const expectedRentFor = (unit, mKey) => {
    const rev = (revsByUnit.get(unit.id) || []).find(r => r.effective_from <= mKey);
    return Number(rev ? rev.monthly_rent : unit.monthly_rent);
  };

  const monthPaid = (unit, mKey) => payAgg.get(`${unit.id}|${mKey}`)?.paid || 0;

  // unpaid months (within the 12-month grid window) for reminders / dues
  const dueMonthsFor = (unit) => {
    const startKey = unit.rent_start ? monthKey(new Date(unit.rent_start)) : null;
    return months
      .filter(m => m.key <= thisMonthKey && (!startKey || m.key >= startKey))
      .map(m => ({ ...m, due: Math.max(expectedRentFor(unit, m.key) - monthPaid(unit, m.key), 0) }))
      .filter(m => m.due > 0);
  };

  const perUnitTotals = useMemo(() => {
    const map = new Map();
    for (const u of units) map.set(u.id, { collected: 0, expenses: 0 });
    for (const p of payments) { const t = map.get(p.unit_id); if (t) t.collected += Number(p.amount); }
    for (const x of unitExpenses) { const t = map.get(x.unit_id); if (t) t.expenses += Number(x.amount); }
    return map;
  }, [units, payments, unitExpenses]);

  const activeUnits = units.filter(u => u.is_active);
  const monthlyIncome = activeUnits.reduce((s, u) => s + expectedRentFor(u, thisMonthKey), 0);
  const collectedThisMonth = payments.filter(p => p.rent_month === thisMonthKey).reduce((s, p) => s + Number(p.amount), 0);
  const dueUnits = activeUnits.filter(u => monthPaid(u, thisMonthKey) < expectedRentFor(u, thisMonthKey));
  const advanceHeld = activeUnits.reduce((s, u) => s + Number(u.advance_deposit || 0), 0);

  // ---------- unit create/edit (records rent revisions) ----------
  const saveRevision = async (unitId, effectiveFrom, rent) => {
    const existing = revisions.find(r => r.unit_id === unitId && r.effective_from === effectiveFrom);
    if (existing) await updateRevision(existing.id, { monthly_rent: rent });
    else await addRevision({ unit_id: unitId, effective_from: effectiveFrom, monthly_rent: rent });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const rent = parseFloat(form.monthly_rent) || 0;
    const payload = {
      name: form.name,
      tenant_name: form.tenant_name || null,
      tenant_phone: form.tenant_phone || null,
      monthly_rent: rent,
      advance_deposit: form.advance_deposit ? parseFloat(form.advance_deposit) : 0,
      rent_start: form.rent_start || null,
      notes: form.notes || '',
      is_active: form.is_active
    };
    try {
      if (editing) {
        await updateRow(editing.id, payload);
        if (rent !== Number(editing.monthly_rent)) {
          await saveRevision(editing.id, `${form.rent_effective}-01`, rent);
        }
      } else {
        const unit = await addRow(payload);
        const eff = monthKey(form.rent_start ? new Date(form.rent_start) : new Date());
        await saveRevision(unit.id, eff, rent);
      }
      setIsAdding(false); setEditing(null); setForm(initialForm);
    } catch (err) {
      alert('Error saving unit: ' + err.message);
    }
  };

  // ---------- collect (supports partial + charges) ----------
  const openCollect = (unit, month) => {
    const remaining = Math.max(expectedRentFor(unit, month) - monthPaid(unit, month), 0);
    setCollecting({ unit, month });
    setCollectForm({ ...initialCollect, amount: remaining || expectedRentFor(unit, month) });
  };

  const handleCollect = async (e) => {
    e.preventDefault();
    try {
      const total = parseFloat(collectForm.amount);
      const charge = collectForm.charge_amount ? parseFloat(collectForm.charge_amount) : 0;
      if (charge > total) { alert('Charges cannot exceed the total amount.'); return; }
      let txId = null;
      if (collectForm.log_income) {
        const { data, error } = await supabase.rpc('process_transaction', {
          p_user_id: user.id,
          p_entity_id: currentEntity.id,
          p_account_id: collectForm.account_id,
          p_category_id: collectForm.category_id,
          p_asset_id: null,
          p_type: 'income',
          p_amount: total,
          p_date: collectForm.date,
          p_description: `Rent — ${collecting.unit.name} (${monthLabel(collecting.month, { month: 'long', year: 'numeric' })})`
        });
        if (error) throw error;
        txId = data;
      }
      await addPayment({
        unit_id: collecting.unit.id,
        rent_month: collecting.month,
        amount: total,
        charge_amount: charge,
        charge_note: collectForm.charge_note || null,
        paid_date: collectForm.date,
        transaction_id: txId,
        notes: ''
      });
      if (collectForm.log_income) await fetchAccounts();
      setCollecting(null);
    } catch (err) {
      alert('Error collecting rent: ' + err.message);
    }
  };

  // ---------- receipt PDF ----------
  const downloadReceipt = (unit, payment) =>
    downloadHtmlAsPdf(
      receiptHtml({ entityName: currentEntity?.name, unit, payment }),
      `rent_receipt_${unit.name.replace(/\s+/g, '_')}_${payment.rent_month.slice(0, 7)}.pdf`
    ).catch(err => alert('Error generating receipt: ' + err.message));

  // ---------- unit expense ----------
  const handleAddExpense = async (e, unit) => {
    e.preventDefault();
    try {
      let txId = null;
      if (expForm.pay_from_account) {
        const { data, error } = await supabase.rpc('process_transaction', {
          p_user_id: user.id,
          p_entity_id: currentEntity.id,
          p_account_id: expForm.account_id,
          p_category_id: expForm.category_id,
          p_asset_id: null,
          p_type: 'expense',
          p_amount: parseFloat(expForm.amount),
          p_date: expForm.date,
          p_description: `${unit.name} — ${expForm.description || 'maintenance'}`
        });
        if (error) throw error;
        txId = data;
      }
      await addUnitExpense({
        unit_id: unit.id,
        date: expForm.date,
        amount: parseFloat(expForm.amount),
        description: expForm.description || '',
        transaction_id: txId
      });
      if (expForm.pay_from_account) await fetchAccounts();
      setExpForm(initialExpense);
    } catch (err) {
      alert('Error saving expense: ' + err.message);
    }
  };

  // ---------- end tenancy: advance settlement ----------
  const openSettle = (unit) => {
    const dues = dueMonthsFor(unit).reduce((s, m) => s + m.due, 0);
    setSettling(unit);
    setSettleForm({ ...initialSettle, dues: dues ? String(Math.round(dues)) : '' });
  };

  const handleSettle = async (e) => {
    e.preventDefault();
    const unit = settling;
    const advance = Number(unit.advance_deposit || 0);
    const dues = parseFloat(settleForm.dues) || 0;
    const deducted = Math.min(dues, advance);
    const refund = Math.max(advance - dues, 0);
    try {
      let refundTxId = null;
      if (settleForm.log_refund && refund > 0) {
        const { data, error } = await supabase.rpc('process_transaction', {
          p_user_id: user.id,
          p_entity_id: currentEntity.id,
          p_account_id: settleForm.account_id,
          p_category_id: settleForm.category_id,
          p_asset_id: null,
          p_type: 'expense',
          p_amount: refund,
          p_date: settleForm.end_date,
          p_description: `Advance refund — ${unit.name} (${unit.tenant_name || 'tenant'})`
        });
        if (error) throw error;
        refundTxId = data;
      }
      if (settleForm.log_dues_income && deducted > 0) {
        // no cash moves — the advance was already in hand, so this is an
        // account-less memo income row (same pattern as shop-due purchases)
        const { error } = await supabase.from('transactions').insert({
          user_id: user.id,
          entity_id: currentEntity.id,
          account_id: null,
          category_id: settleForm.dues_category_id,
          type: 'income',
          amount: deducted,
          date: settleForm.end_date,
          description: `Rent dues kept from advance — ${unit.name} (${unit.tenant_name || 'tenant'})`
        });
        if (error) throw error;
      }
      await addTenancy({
        unit_id: unit.id,
        tenant_name: unit.tenant_name || '—',
        tenant_phone: unit.tenant_phone || null,
        start_date: unit.rent_start || null,
        end_date: settleForm.end_date,
        monthly_rent: expectedRentFor(unit, thisMonthKey),
        advance_deposit: advance,
        dues_deducted: deducted,
        advance_returned: refund,
        refund_transaction_id: refundTxId,
        notes: settleForm.notes || ''
      });
      await updateRow(unit.id, { tenant_name: null, tenant_phone: null, advance_deposit: 0, is_active: false, rent_start: null });
      if (settleForm.log_refund && refund > 0) await fetchAccounts();
      setSettling(null);
    } catch (err) {
      alert('Error ending tenancy: ' + err.message);
    }
  };

  // ---------- WhatsApp reminder ----------
  const waLink = (unit) => {
    const dues = dueMonthsFor(unit);
    if (!dues.length || !unit.tenant_phone) return null;
    const list = dues.map(d => `${d.label} ${fmt(d.due)}`).join(', ');
    const total = dues.reduce((s, d) => s + d.due, 0);
    const msg = `আসসালামু আলাইকুম${unit.tenant_name ? ' ' + unit.tenant_name : ''}, ${unit.name} এর ভাড়া বাকি আছে: ${list}। মোট ${fmt(total)}। দয়া করে পরিশোধ করবেন। ধন্যবাদ।`;
    return `https://wa.me/${intlPhone(unit.tenant_phone)}?text=${encodeURIComponent(msg)}`;
  };

  // ---------- yearly statement PDF ----------
  const generateStatement = async () => {
    const y = stmtYear;
    const yearMonths = Array.from({ length: 12 }, (_, i) => `${y}-${String(i + 1).padStart(2, '0')}-01`);
    const sections = units.map(u => {
      const startKey = u.rent_start ? monthKey(new Date(u.rent_start)) : null;
      let expT = 0, paidT = 0;
      const rows = yearMonths.map(k => {
        const skip = (startKey && k < startKey) || k > thisMonthKey;
        const exp = skip ? 0 : expectedRentFor(u, k);
        const paid = monthPaid(u, k);
        expT += exp; paidT += paid;
        return [monthLabel(k, { month: 'long' }), fmt(exp), fmt(paid), fmt(Math.max(exp - paid, 0))];
      });
      const xp = unitExpenses.filter(x => x.unit_id === u.id && x.date.startsWith(String(y)))
        .reduce((s, x) => s + Number(x.amount), 0);
      rows.push(['TOTAL', fmt(expT), fmt(paidT), fmt(Math.max(expT - paidT, 0))]);
      rows.push([`Unit expenses ${y}`, '', fmt(xp), '']);
      rows.push([`Net income ${y}`, '', fmt(paidT - xp), '']);
      return {
        title: `${u.name}${u.tenant_name ? ` — ${u.tenant_name}` : ''}`,
        head: ['Month', 'Expected', 'Collected', 'Due'],
        rows,
        boldRows: [12, 14]
      };
    });
    const fyTotal = (startYear) => payments
      .filter(p => p.rent_month >= `${startYear}-07-01` && p.rent_month <= `${startYear + 1}-06-01`)
      .reduce((s, p) => s + Number(p.amount), 0);
    sections.push({
      title: 'Rental income by fiscal year (Jul–Jun) — for tax return',
      head: ['Fiscal Year', 'Rent Collected'],
      rows: [
        [`FY ${y - 1}-${String(y).slice(2)}`, fmt(fyTotal(y - 1))],
        [`FY ${y}-${String(y + 1).slice(2)}`, fmt(fyTotal(y))]
      ]
    });
    await downloadHtmlAsPdf(
      multiSectionHtml({
        entityName: currentEntity?.name,
        title: `Rent Statement ${y}`,
        subtitle: `All units · January – December ${y}`,
        sections
      }),
      `rent_statement_${y}.pdf`
    ).catch(err => alert('Error generating statement: ' + err.message));
    setStmtOpen(false);
  };

  if (loading) return <div className="text-white/50 p-6">Loading rental units...</div>;

  const inputCls = 'w-full bg-[#12122a] border border-white/10 rounded-xl px-4 py-2.5 text-white focus:outline-none focus:border-teal-500/50';
  const labelCls = 'block text-sm text-white/60 mb-1';

  return (
    <div className="space-y-6 animate-in">
      <div className="flex flex-wrap justify-between items-center gap-3">
        <div>
          <h1 className="text-2xl font-bold text-white">Rent Management</h1>
          <p className="text-white/40 text-sm mt-1">Units, tenants, partial collection, receipts & settlements.</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => setStmtOpen(true)}
            className="flex items-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 text-white/80 px-4 py-2 rounded-xl transition-colors"
          >
            <FileText size={16} /> Statement
          </button>
          <button
            onClick={() => { setIsAdding(true); setEditing(null); setForm(initialForm); }}
            className="flex items-center gap-2 bg-teal-500 hover:bg-teal-600 text-white px-4 py-2 rounded-xl transition-colors shadow-lg shadow-teal-500/20"
          >
            <Plus size={18} /> Add Unit
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard title="Active Units" value={activeUnits.length} icon={Building2} gradient={["#2dd4bf", "#14b8a6"]} iconBg="bg-teal-500/10" />
        <StatCard title="Expected / Month" value={fmt(monthlyIncome)} icon={Home} gradient={["#34d399", "#10b981"]} iconBg="bg-emerald-500/10" />
        <StatCard title="Collected This Month" value={`${fmt(collectedThisMonth)}${dueUnits.length ? ` (${dueUnits.length} due)` : ''}`} icon={Home} gradient={dueUnits.length ? ["#f59e0b", "#d97706"] : ["#34d399", "#10b981"]} iconBg="bg-amber-500/10" />
        <StatCard title="Advance Held" value={fmt(advanceHeld)} icon={Wallet} gradient={["#a78bfa", "#8b5cf6"]} iconBg="bg-violet-500/10" />
      </div>

      {(isAdding || editing) && (
        <div className="bg-[#1a1a2e] border border-white/10 rounded-2xl p-6">
          <h2 className="text-lg font-semibold text-white mb-4">{editing ? 'Edit Unit' : 'New Rental Unit'}</h2>
          <form onSubmit={handleSubmit} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <div>
              <label className={labelCls}>Unit Name</label>
              <input required type="text" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="e.g. 2nd Floor Flat-A" className={inputCls} />
            </div>
            <div>
              <label className={labelCls}>Tenant Name</label>
              <input type="text" value={form.tenant_name || ''} onChange={e => setForm({ ...form, tenant_name: e.target.value })} className={inputCls} />
            </div>
            <div>
              <label className={labelCls}>Tenant Phone</label>
              <input type="tel" value={form.tenant_phone || ''} onChange={e => setForm({ ...form, tenant_phone: e.target.value })} className={inputCls} />
            </div>
            <div>
              <label className={labelCls}>Monthly Rent</label>
              <input required type="number" step="0.01" value={form.monthly_rent} onChange={e => setForm({ ...form, monthly_rent: e.target.value })} className={inputCls} />
            </div>
            {editing && parseFloat(form.monthly_rent) !== Number(editing.monthly_rent) && (
              <div>
                <label className={labelCls}>New Rent Effective From</label>
                <input required type="month" value={form.rent_effective} onChange={e => setForm({ ...form, rent_effective: e.target.value })} className={inputCls} />
                <p className="text-xs text-white/35 mt-1">Older months keep the previous rent in dues & statements.</p>
              </div>
            )}
            <div>
              <label className={labelCls}>Advance / Security Deposit</label>
              <input type="number" step="0.01" value={form.advance_deposit || ''} onChange={e => setForm({ ...form, advance_deposit: e.target.value })} className={inputCls} />
            </div>
            <div>
              <label className={labelCls}>Rent Since</label>
              <input type="date" value={form.rent_start || ''} onChange={e => setForm({ ...form, rent_start: e.target.value })} className={inputCls} />
            </div>
            <div className="flex items-center gap-2">
              <input type="checkbox" id="unit_active" checked={form.is_active} onChange={e => setForm({ ...form, is_active: e.target.checked })} className="w-4 h-4 rounded accent-teal-500" />
              <label htmlFor="unit_active" className="text-sm text-white/80">Currently rented</label>
            </div>
            <div className="sm:col-span-2 lg:col-span-3 flex justify-end gap-3">
              <button type="button" onClick={() => { setIsAdding(false); setEditing(null); }} className="px-5 py-2.5 rounded-xl text-white/60 hover:text-white hover:bg-white/5 transition-colors">Cancel</button>
              <button type="submit" className="bg-teal-500 hover:bg-teal-600 text-white px-6 py-2.5 rounded-xl shadow-lg shadow-teal-500/20 transition-all font-medium">Save Unit</button>
            </div>
          </form>
        </div>
      )}

      {/* ---------- collect modal (partial + charges) ---------- */}
      {collecting && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-[#1a1a2e] border border-white/10 rounded-2xl p-6 w-full max-w-md shadow-2xl max-h-[90vh] overflow-y-auto">
            <h2 className="text-xl font-semibold text-white mb-2">Collect Rent</h2>
            <p className="text-sm text-white/50 mb-1">
              {collecting.unit.name} — {monthLabel(collecting.month, { month: 'long', year: 'numeric' })}
              {collecting.unit.tenant_name && <span> · {collecting.unit.tenant_name}</span>}
            </p>
            <p className="text-xs text-white/40 mb-5">
              Expected {fmt(expectedRentFor(collecting.unit, collecting.month))} · already received {fmt(monthPaid(collecting.unit, collecting.month))} — partial amounts are fine.
            </p>
            <form onSubmit={handleCollect} className="space-y-4">
              <div>
                <label className={labelCls}>Amount Received (total)</label>
                <input required type="number" step="0.01" min="0.01" value={collectForm.amount} onChange={e => setCollectForm({ ...collectForm, amount: e.target.value })} className={inputCls} />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className={labelCls}>Incl. Charges (optional)</label>
                  <input type="number" step="0.01" min="0" value={collectForm.charge_amount} onChange={e => setCollectForm({ ...collectForm, charge_amount: e.target.value })} placeholder="0" className={inputCls} />
                </div>
                <div>
                  <label className={labelCls}>Charge Note</label>
                  <input type="text" value={collectForm.charge_note} onChange={e => setCollectForm({ ...collectForm, charge_note: e.target.value })} placeholder="gas/water/service" className={inputCls} />
                </div>
              </div>
              <div>
                <label className={labelCls}>Date Received</label>
                <input required type="date" value={collectForm.date} onChange={e => setCollectForm({ ...collectForm, date: e.target.value })} className={inputCls} />
              </div>
              <div className="flex items-center gap-2">
                <input type="checkbox" id="log_income" checked={collectForm.log_income} onChange={e => setCollectForm({ ...collectForm, log_income: e.target.checked })} className="w-4 h-4 rounded accent-teal-500" />
                <label htmlFor="log_income" className="text-sm text-white/80">Log as income transaction (adds to account balance)</label>
              </div>
              {collectForm.log_income && (
                <>
                  <div>
                    <label className={labelCls}>Deposit To Account</label>
                    <select required value={collectForm.account_id} onChange={e => setCollectForm({ ...collectForm, account_id: e.target.value })} className={inputCls}>
                      <option value="">Select an account...</option>
                      {accounts.map(a => <option key={a.id} value={a.id}>{a.name} ({a.currency}{a.current_balance})</option>)}
                    </select>
                  </div>
                  <div>
                    <label className={labelCls}>Income Category</label>
                    <select required value={collectForm.category_id} onChange={e => setCollectForm({ ...collectForm, category_id: e.target.value })} className={inputCls}>
                      <option value="">Select a category...</option>
                      {incomeCategories.map(c => <option key={c.id} value={c.id}>{c.icon} {c.name}</option>)}
                    </select>
                  </div>
                </>
              )}
              <div className="flex justify-end gap-3 mt-6">
                <button type="button" onClick={() => setCollecting(null)} className="px-5 py-2.5 rounded-xl text-white/60 hover:text-white hover:bg-white/5 transition-colors">Cancel</button>
                <button type="submit" className="bg-teal-500 hover:bg-teal-600 text-white px-6 py-2.5 rounded-xl shadow-lg shadow-teal-500/20 transition-all font-medium">Record Payment</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ---------- month detail modal (payments of one month) ---------- */}
      {monthView && (() => {
        const { unit, month } = monthView;
        const agg = payAgg.get(`${unit.id}|${month}`) || { paid: 0, list: [] };
        const expected = expectedRentFor(unit, month);
        const remaining = Math.max(expected - agg.paid, 0);
        return (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-[#1a1a2e] border border-white/10 rounded-2xl p-6 w-full max-w-md shadow-2xl max-h-[90vh] overflow-y-auto">
              <h2 className="text-xl font-semibold text-white mb-1">{monthLabel(month, { month: 'long', year: 'numeric' })}</h2>
              <p className="text-sm text-white/50 mb-4">
                {unit.name} · expected {fmt(expected)} · received {fmt(agg.paid)}
                {remaining > 0 && <span className="text-amber-400"> · {fmt(remaining)} due</span>}
              </p>
              <div className="space-y-2 mb-5">
                {agg.list.map(p => (
                  <div key={p.id} className="flex items-center justify-between bg-white/5 border border-white/10 rounded-xl px-4 py-2.5">
                    <div>
                      <p className="text-white text-sm font-medium">{fmt(p.amount)}
                        {Number(p.charge_amount) > 0 && <span className="text-white/40 font-normal"> (incl. {fmt(p.charge_amount)} {p.charge_note || 'charges'})</span>}
                      </p>
                      <p className="text-white/40 text-xs">{new Date(p.paid_date).toLocaleDateString()}{p.transaction_id ? ' · in accounts' : ''}</p>
                    </div>
                    <div className="flex gap-1.5">
                      <button onClick={() => downloadReceipt(unit, p)} title="Download receipt PDF" className="text-white/40 hover:text-teal-400 p-2 rounded-lg hover:bg-teal-500/10">
                        <Receipt size={15} />
                      </button>
                      <button
                        onClick={() => { if (confirm(`Remove this ${fmt(p.amount)} payment record? (Any linked income transaction stays.)`)) deletePayment(p.id).catch(err => alert(err.message)); }}
                        className="text-white/40 hover:text-red-400 p-2 rounded-lg hover:bg-red-500/10"
                      >
                        <Trash2 size={15} />
                      </button>
                    </div>
                  </div>
                ))}
                {agg.list.length === 0 && <p className="text-white/40 text-sm text-center py-3">No payments recorded for this month.</p>}
              </div>
              <div className="flex justify-end gap-3">
                <button onClick={() => setMonthView(null)} className="px-5 py-2.5 rounded-xl text-white/60 hover:text-white hover:bg-white/5 transition-colors">Close</button>
                <button
                  onClick={() => { setMonthView(null); openCollect(unit, month); }}
                  className="bg-teal-500 hover:bg-teal-600 text-white px-5 py-2.5 rounded-xl shadow-lg shadow-teal-500/20 font-medium"
                >
                  Collect{remaining > 0 ? ` ${fmt(remaining)}` : ' More'}
                </button>
              </div>
            </div>
          </div>
        );
      })()}

      {/* ---------- end-tenancy / advance settlement modal ---------- */}
      {settling && (() => {
        const advance = Number(settling.advance_deposit || 0);
        const dues = parseFloat(settleForm.dues) || 0;
        const deducted = Math.min(dues, advance);
        const refund = Math.max(advance - dues, 0);
        const shortfall = Math.max(dues - advance, 0);
        return (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-[#1a1a2e] border border-white/10 rounded-2xl p-6 w-full max-w-lg shadow-2xl max-h-[90vh] overflow-y-auto">
              <h2 className="text-xl font-semibold text-white mb-1">End Tenancy — {settling.name}</h2>
              <p className="text-sm text-white/50 mb-5">{settling.tenant_name || 'Tenant'} is leaving. Settle dues against the advance deposit.</p>
              <form onSubmit={handleSettle} className="space-y-4">
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className={labelCls}>Leaving Date</label>
                    <input required type="date" value={settleForm.end_date} onChange={e => setSettleForm({ ...settleForm, end_date: e.target.value })} className={inputCls} />
                  </div>
                  <div>
                    <label className={labelCls}>Unpaid Dues</label>
                    <input type="number" step="0.01" min="0" value={settleForm.dues} onChange={e => setSettleForm({ ...settleForm, dues: e.target.value })} placeholder="0" className={inputCls} />
                    <p className="text-xs text-white/35 mt-1">Pre-filled from unpaid months — adjust if needed.</p>
                  </div>
                </div>

                <div className="bg-white/5 border border-white/10 rounded-xl p-4 text-sm space-y-1.5">
                  <div className="flex justify-between text-white/60"><span>Advance held</span><span className="text-white">{fmt(advance)}</span></div>
                  <div className="flex justify-between text-white/60"><span>Dues deducted from advance</span><span className="text-amber-400">− {fmt(deducted)}</span></div>
                  <div className="flex justify-between font-medium border-t border-white/10 pt-1.5 text-white/80">
                    <span>Advance to return</span><span className="text-emerald-400">{fmt(refund)}</span>
                  </div>
                  {shortfall > 0 && (
                    <p className="text-red-400/90 text-xs pt-1">
                      Dues exceed the advance — tenant still owes {fmt(shortfall)}. Collect it separately (Dena-Paona is handy for this).
                    </p>
                  )}
                </div>

                {refund > 0 && (
                  <>
                    <div className="flex items-center gap-2">
                      <input type="checkbox" id="log_refund" checked={settleForm.log_refund} onChange={e => setSettleForm({ ...settleForm, log_refund: e.target.checked })} className="w-4 h-4 rounded accent-teal-500" />
                      <label htmlFor="log_refund" className="text-sm text-white/80">Log the {fmt(refund)} refund as an expense (cash leaves an account)</label>
                    </div>
                    {settleForm.log_refund && (
                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <label className={labelCls}>Refund From Account</label>
                          <select required value={settleForm.account_id} onChange={e => setSettleForm({ ...settleForm, account_id: e.target.value })} className={inputCls}>
                            <option value="">Select an account...</option>
                            {accounts.map(a => <option key={a.id} value={a.id}>{a.name} ({a.currency}{a.current_balance})</option>)}
                          </select>
                        </div>
                        <div>
                          <label className={labelCls}>Expense Category</label>
                          <select required value={settleForm.category_id} onChange={e => setSettleForm({ ...settleForm, category_id: e.target.value })} className={inputCls}>
                            <option value="">Select a category...</option>
                            {expenseCategories.map(c => <option key={c.id} value={c.id}>{c.icon} {c.name}</option>)}
                          </select>
                        </div>
                      </div>
                    )}
                  </>
                )}

                {deducted > 0 && (
                  <>
                    <div className="flex items-center gap-2">
                      <input type="checkbox" id="log_dues_income" checked={settleForm.log_dues_income} onChange={e => setSettleForm({ ...settleForm, log_dues_income: e.target.checked })} className="w-4 h-4 rounded accent-teal-500" />
                      <label htmlFor="log_dues_income" className="text-sm text-white/80">Log the {fmt(deducted)} kept dues as rent income (memo — no account movement)</label>
                    </div>
                    {settleForm.log_dues_income && (
                      <div>
                        <label className={labelCls}>Income Category</label>
                        <select required value={settleForm.dues_category_id} onChange={e => setSettleForm({ ...settleForm, dues_category_id: e.target.value })} className={inputCls}>
                          <option value="">Select a category...</option>
                          {incomeCategories.map(c => <option key={c.id} value={c.id}>{c.icon} {c.name}</option>)}
                        </select>
                      </div>
                    )}
                  </>
                )}

                <div>
                  <label className={labelCls}>Notes</label>
                  <input type="text" value={settleForm.notes} onChange={e => setSettleForm({ ...settleForm, notes: e.target.value })} placeholder="condition of flat, keys returned…" className={inputCls} />
                </div>

                <p className="text-xs text-white/35">
                  The tenant moves to this unit's history, and the unit becomes vacant (advance reset, marked not rented).
                </p>
                <div className="flex justify-end gap-3">
                  <button type="button" onClick={() => setSettling(null)} className="px-5 py-2.5 rounded-xl text-white/60 hover:text-white hover:bg-white/5 transition-colors">Cancel</button>
                  <button type="submit" className="bg-red-500 hover:bg-red-600 text-white px-6 py-2.5 rounded-xl shadow-lg shadow-red-500/20 transition-all font-medium">End Tenancy & Settle</button>
                </div>
              </form>
            </div>
          </div>
        );
      })()}

      {/* ---------- statement modal ---------- */}
      {stmtOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-[#1a1a2e] border border-white/10 rounded-2xl p-6 w-full max-w-sm shadow-2xl">
            <h2 className="text-xl font-semibold text-white mb-4">Yearly Rent Statement</h2>
            <label className={labelCls}>Year</label>
            <select value={stmtYear} onChange={e => setStmtYear(Number(e.target.value))} className={inputCls}>
              {[0, 1, 2].map(i => {
                const y = new Date().getFullYear() - i;
                return <option key={y} value={y}>{y}</option>;
              })}
            </select>
            <p className="text-xs text-white/35 mt-2">Per-unit expected/collected/due for every month, unit expenses, net income, plus Jul–Jun fiscal-year totals for the tax return.</p>
            <div className="flex justify-end gap-3 mt-5">
              <button onClick={() => setStmtOpen(false)} className="px-5 py-2.5 rounded-xl text-white/60 hover:text-white hover:bg-white/5 transition-colors">Cancel</button>
              <button onClick={generateStatement} className="bg-teal-500 hover:bg-teal-600 text-white px-5 py-2.5 rounded-xl shadow-lg shadow-teal-500/20 font-medium">Download PDF</button>
            </div>
          </div>
        </div>
      )}

      {/* ---------- unit cards ---------- */}
      <div className="space-y-4">
        {units.map(unit => {
          const dues = dueMonthsFor(unit);
          const duesTotal = dues.reduce((s, m) => s + m.due, 0);
          const wa = unit.is_active ? waLink(unit) : null;
          const totals = perUnitTotals.get(unit.id) || { collected: 0, expenses: 0 };
          const history = tenancies.filter(t => t.unit_id === unit.id);
          const expenses = unitExpenses.filter(x => x.unit_id === unit.id);
          const expanded = expandedId === unit.id;
          return (
            <div key={unit.id} className={`bg-[#1a1a2e] border rounded-2xl p-5 ${unit.is_active ? 'border-white/10' : 'border-white/5 opacity-70'}`}>
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-4">
                <div className="flex items-center gap-3">
                  <div className="w-11 h-11 rounded-xl bg-teal-500/10 flex items-center justify-center">
                    <Home className="text-teal-400" size={20} />
                  </div>
                  <div>
                    <h3 className="text-white font-medium">
                      {unit.name} <span className="text-white/40 text-sm font-normal">· {fmt(expectedRentFor(unit, thisMonthKey))}/mo</span>
                      {duesTotal > 0 && unit.is_active && <span className="ml-2 px-2 py-0.5 rounded text-[10px] font-bold bg-red-500/15 text-red-400 align-middle">DUE {fmt(duesTotal)}</span>}
                    </h3>
                    <p className="text-white/40 text-xs">
                      {unit.tenant_name || (unit.is_active ? 'No tenant' : 'Vacant')}
                      {unit.tenant_phone && (
                        <a href={`tel:${unit.tenant_phone}`} className="text-cyan-400/80 hover:text-cyan-400 ml-2"><Phone size={10} className="inline -mt-0.5" /> {unit.tenant_phone}</a>
                      )}
                      {Number(unit.advance_deposit) > 0 && <span className="ml-2">· Advance {fmt(unit.advance_deposit)}</span>}
                    </p>
                  </div>
                </div>
                <div className="flex gap-2 flex-wrap">
                  {wa && (
                    <a href={wa} target="_blank" rel="noreferrer" title="Send WhatsApp rent reminder" className="text-emerald-400 hover:text-emerald-300 p-2 bg-emerald-500/10 hover:bg-emerald-500/20 rounded-lg">
                      <MessageCircle size={15} />
                    </a>
                  )}
                  {unit.tenant_name && unit.is_active && (
                    <button onClick={() => openSettle(unit)} title="End tenancy — settle advance & dues" className="text-white/40 hover:text-red-400 p-2 bg-white/5 hover:bg-red-500/10 rounded-lg">
                      <LogOut size={15} />
                    </button>
                  )}
                  <button onClick={() => setExpandedId(expanded ? null : unit.id)} title="Expenses & tenant history" className={`p-2 rounded-lg ${expanded ? 'text-teal-400 bg-teal-500/10' : 'text-white/40 hover:text-teal-400 bg-white/5 hover:bg-teal-500/10'}`}>
                    {expanded ? <ChevronUp size={15} /> : <ChevronDown size={15} />}
                  </button>
                  <button onClick={() => { setEditing(unit); setForm({ ...initialForm, ...unit, rent_effective: new Date().toISOString().slice(0, 7) }); setIsAdding(false); }} className="text-white/40 hover:text-cyan-400 p-2 bg-white/5 hover:bg-cyan-500/10 rounded-lg">
                    <Edit2 size={15} />
                  </button>
                  <button onClick={() => { if (confirm(`Delete "${unit.name}" and its payment history?`)) deleteRow(unit.id).then(fetchPayments).catch(err => alert(err.message)); }} className="text-white/40 hover:text-red-400 p-2 bg-white/5 hover:bg-red-500/10 rounded-lg">
                    <Trash2 size={15} />
                  </button>
                </div>
              </div>

              {/* 12-month collection grid: full / partial / due */}
              <div className="flex gap-1.5 overflow-x-auto pb-1">
                {[...months].reverse().map(m => {
                  const expected = expectedRentFor(unit, m.key);
                  const paid = monthPaid(unit, m.key);
                  const hasPayments = (payAgg.get(`${unit.id}|${m.key}`)?.list.length || 0) > 0;
                  const isFuture = m.key > thisMonthKey;
                  const beforeStart = unit.rent_start && m.key < monthKey(new Date(unit.rent_start));
                  const full = expected > 0 ? paid >= expected : hasPayments;
                  const partial = paid > 0 && !full;
                  const disabled = isFuture || beforeStart || (!unit.is_active && !hasPayments);
                  return (
                    <button
                      key={m.key}
                      disabled={disabled}
                      onClick={() => {
                        if (hasPayments) setMonthView({ unit, month: m.key });
                        else openCollect(unit, m.key);
                      }}
                      title={hasPayments ? `Received ${fmt(paid)} of ${fmt(expected)} — click for details` : isFuture ? 'Future month' : 'Click to collect'}
                      className={`shrink-0 w-14 py-2 rounded-lg text-[11px] font-medium border transition-all ${
                        full
                          ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30'
                          : partial
                            ? 'bg-amber-500/20 text-amber-400 border-amber-500/40 hover:bg-amber-500/30'
                            : disabled
                              ? 'bg-white/[0.02] text-white/20 border-white/5 cursor-default'
                              : m.key === thisMonthKey
                                ? 'bg-amber-500/15 text-amber-400 border-amber-500/30 hover:bg-amber-500/25'
                                : 'bg-red-500/10 text-red-400/80 border-red-500/20 hover:bg-red-500/20'
                      }`}
                    >
                      {m.label.split(' ')[0]}
                      <div className="text-[9px] opacity-70">
                        {full ? '✓' : partial ? 'part' : disabled ? '·' : 'due'}
                      </div>
                    </button>
                  );
                })}
              </div>

              {/* expanded: expenses + tenant history */}
              {expanded && (
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-4 pt-4 border-t border-white/5">
                  <div>
                    <h4 className="text-white/70 text-sm font-medium mb-2 flex items-center gap-1.5">
                      <Wrench size={14} className="text-teal-400" /> Unit Expenses
                      <span className="text-white/35 font-normal">· total {fmt(totals.expenses)} · net income {fmt(totals.collected - totals.expenses)}</span>
                    </h4>
                    <form onSubmit={e => handleAddExpense(e, unit)} className="space-y-2 mb-3">
                      <div className="grid grid-cols-3 gap-2">
                        <input required type="date" value={expForm.date} onChange={e => setExpForm({ ...expForm, date: e.target.value })} className={inputCls + ' !px-2 text-sm'} />
                        <input required type="number" step="0.01" min="0.01" placeholder="Amount" value={expForm.amount} onChange={e => setExpForm({ ...expForm, amount: e.target.value })} className={inputCls + ' !px-2 text-sm'} />
                        <input type="text" placeholder="Repair, paint…" value={expForm.description} onChange={e => setExpForm({ ...expForm, description: e.target.value })} className={inputCls + ' !px-2 text-sm'} />
                      </div>
                      <div className="flex flex-wrap items-center gap-2">
                        <label className="flex items-center gap-1.5 text-xs text-white/60">
                          <input type="checkbox" checked={expForm.pay_from_account} onChange={e => setExpForm({ ...expForm, pay_from_account: e.target.checked })} className="w-3.5 h-3.5 rounded accent-teal-500" />
                          Pay from account
                        </label>
                        {expForm.pay_from_account && (
                          <>
                            <select required value={expForm.account_id} onChange={e => setExpForm({ ...expForm, account_id: e.target.value })} className="bg-[#12122a] border border-white/10 rounded-lg px-2 py-1.5 text-white text-xs focus:outline-none">
                              <option value="">Account…</option>
                              {accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
                            </select>
                            <select required value={expForm.category_id} onChange={e => setExpForm({ ...expForm, category_id: e.target.value })} className="bg-[#12122a] border border-white/10 rounded-lg px-2 py-1.5 text-white text-xs focus:outline-none">
                              <option value="">Category…</option>
                              {expenseCategories.map(c => <option key={c.id} value={c.id}>{c.icon} {c.name}</option>)}
                            </select>
                          </>
                        )}
                        <button type="submit" className="ml-auto text-xs bg-teal-500 hover:bg-teal-600 text-white px-3 py-1.5 rounded-lg font-medium">Add Expense</button>
                      </div>
                    </form>
                    <div className="space-y-1.5 max-h-44 overflow-y-auto">
                      {expenses.map(x => (
                        <div key={x.id} className="flex items-center justify-between bg-white/[0.03] rounded-lg px-3 py-1.5 text-sm">
                          <span className="text-white/60 text-xs">{new Date(x.date).toLocaleDateString()} · {x.description || 'Expense'}{x.transaction_id ? '' : ' (memo)'}</span>
                          <span className="flex items-center gap-2">
                            <span className="text-red-400/90">{fmt(x.amount)}</span>
                            <button onClick={() => { if (confirm('Remove this expense record? (Any linked transaction stays.)')) deleteUnitExpense(x.id).catch(err => alert(err.message)); }} className="text-white/25 hover:text-red-400"><Trash2 size={12} /></button>
                          </span>
                        </div>
                      ))}
                      {expenses.length === 0 && <p className="text-white/30 text-xs">No expenses recorded for this unit.</p>}
                    </div>
                  </div>

                  <div>
                    <h4 className="text-white/70 text-sm font-medium mb-2">Past Tenants</h4>
                    <div className="space-y-1.5 max-h-56 overflow-y-auto">
                      {history.map(t => (
                        <div key={t.id} className="bg-white/[0.03] rounded-lg px-3 py-2 text-xs">
                          <p className="text-white/80 font-medium">{t.tenant_name}
                            <span className="text-white/40 font-normal"> · {t.start_date ? new Date(t.start_date).toLocaleDateString('en-US', { month: 'short', year: 'numeric' }) : '?'} → {new Date(t.end_date).toLocaleDateString('en-US', { month: 'short', year: 'numeric' })}</span>
                          </p>
                          <p className="text-white/40 mt-0.5">
                            Rent {fmt(t.monthly_rent)} · Advance {fmt(t.advance_deposit)}
                            {Number(t.dues_deducted) > 0 && <span className="text-amber-400/90"> · dues kept {fmt(t.dues_deducted)}</span>}
                            {Number(t.advance_returned) > 0 && <span className="text-emerald-400/90"> · returned {fmt(t.advance_returned)}</span>}
                          </p>
                          {t.notes && <p className="text-white/30 mt-0.5">{t.notes}</p>}
                        </div>
                      ))}
                      {history.length === 0 && <p className="text-white/30 text-xs">No previous tenants recorded. Ending a tenancy archives the tenant here.</p>}
                    </div>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {units.length === 0 && !isAdding && (
        <div className="text-center py-12 border border-white/5 rounded-2xl bg-white/[0.02]">
          <Building2 className="mx-auto text-white/20 mb-4" size={48} />
          <h3 className="text-white/60 font-medium">No rental units</h3>
          <p className="text-white/40 text-sm mt-1">Add flats/shops you rent out and track collection month by month.</p>
        </div>
      )}
    </div>
  );
}
